### ISSUE TITLE
Data structure mismatch

### ISSUE THREAD

**Issue by patrickmair** [teamdatatonic/looker-gcp-control#2]
I tried setting this up but the current Stackdriver export doesn't seem to match what is here.  I had to update my database naming convention to match:

`x.y.cloudaudit_googleapis_com_activity_*` instead of:
`x.y.cloudaudit_googleapis_com_data_access_*`

Which is easy enough.  Once updated though, I'm getting errors on the structures contained in the `_payload.servicedata_v1_bigquery` nest.

Is this code potentially out of date with the current export format?

**Comment by andrewpowelldatatonic** [comment]
Hi, how did you set up the Stackdriver Logging exports? Activity logs are quite different to data access audit logs, see here for more information: https://cloud.google.com/logging/docs/audit/#top_of_page.
